#!/usr/bin/env python
"""
Stacked ensemble for the neuro-morbidity Outcome.

Level-0 (per-component XGBoost heads): EEG, CT, MRI -- the three components that
compose Outcome (BHMeds=0 in this cohort, so Outcome == OR(EEG, CT, MRI)). Each
head uses all 811 biomarkers (the control feature set) to predict its own
component.

Level-1 (PURE stacking): a meta-model trained ONLY on the level-0 predicted
probabilities to predict the composite Outcome. Meta-features are leakage-safe:
generated by 5-fold out-of-fold (cross-fitted) prediction on train; heads are
then refit on the full train set to score the test set.

Meta-learners compared (all on the 3 component probabilities):
  - Logistic regression (regularized)   [primary]
  - Noisy-OR analytic baseline          1 - prod(1 - p_i)
  - Shallow XGBoost                      reference (captures interactions)

Evaluated on the same real-patient test individuals as the control model, for a
head-to-head comparison against the all-biomarker control baseline.
"""

import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import xgboost
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    average_precision_score,
    balanced_accuracy_score,
    brier_score_loss,
    f1_score,
    roc_auc_score,
)
from sklearn.model_selection import StratifiedKFold

SCRIPT_DIR = Path(__file__).resolve().parent
CONTROL_DIR = SCRIPT_DIR.parent / "Control Model"
RANDOM_STATE = 42
N_FOLDS = 5
COMPONENTS = ["EEG", "CT", "MRI"]


def make_head():
    return xgboost.XGBClassifier(
        objective="binary:logistic", random_state=RANDOM_STATE, eval_metric="aucpr"
    )


# ---------------------------------------------------------------------------
# Load features, per-component labels and Outcome (all aligned by uid).
# ---------------------------------------------------------------------------
X_train = pd.read_csv(CONTROL_DIR / "X_train_control.csv", index_col=0)
X_test = pd.read_csv(CONTROL_DIR / "X_test_control.csv", index_col=0)
comp_tr = pd.read_csv(CONTROL_DIR / "outcome_components_train.csv", index_col=0)
comp_te = pd.read_csv(CONTROL_DIR / "outcome_components_test.csv", index_col=0)
assert X_train.index.equals(comp_tr.index), "train uid order mismatch"
assert X_test.index.equals(comp_te.index), "test uid order mismatch"

y_train_out = comp_tr["Outcome"].astype(int)
y_test_out = comp_te["Outcome"].astype(int)
print(f"X_train {X_train.shape}, X_test {X_test.shape}")
print(f"Outcome prevalence -- train {y_train_out.mean():.3f}, test {y_test_out.mean():.3f}")

# ---------------------------------------------------------------------------
# Level-0: leakage-safe out-of-fold (cross-fitted) meta-features on train.
# Folds are stratified on Outcome (the meta target) and shared across heads.
# ---------------------------------------------------------------------------
skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_STATE)
folds = list(skf.split(X_train, y_train_out))
oof = pd.DataFrame(index=X_train.index, columns=[f"{c}_pred" for c in COMPONENTS], dtype=float)

print("\nLevel-0 out-of-fold heads:")
for comp in COMPONENTS:
    y_comp = comp_tr[comp].astype(int).values
    col = oof.columns.get_loc(f"{comp}_pred")
    for tr_idx, va_idx in folds:
        m = make_head()
        m.fit(X_train.iloc[tr_idx], y_comp[tr_idx])
        oof.iloc[va_idx, col] = m.predict_proba(X_train.iloc[va_idx])[:, 1]
    auc = roc_auc_score(y_comp, oof[f"{comp}_pred"].values)
    ap = average_precision_score(y_comp, oof[f"{comp}_pred"].values)
    print(f"  {comp:4s}: OOF AUROC {auc:.4f}  AUPRC {ap:.4f}  (n_pos={int(y_comp.sum())})")

assert not oof.isna().any().any(), "OOF matrix has missing entries"

# ---------------------------------------------------------------------------
# Level-0: refit each head on FULL train, save, and score the test set.
# ---------------------------------------------------------------------------
test_feats = pd.DataFrame(index=X_test.index, columns=[f"{c}_pred" for c in COMPONENTS], dtype=float)
head_test_perf = {}
for comp in COMPONENTS:
    m = make_head()
    m.fit(X_train, comp_tr[comp].astype(int))
    m.save_model(str(SCRIPT_DIR / f"head_{comp}.json"))
    p = m.predict_proba(X_test)[:, 1]
    test_feats[f"{comp}_pred"] = p
    yc = comp_te[comp].astype(int).values
    head_test_perf[comp] = {
        "AUROC": round(roc_auc_score(yc, p), 4),
        "AUPRC": round(average_precision_score(yc, p), 4),
        "n_pos_test": int(yc.sum()),
    }

oof.to_csv(SCRIPT_DIR / "oof_train_components.csv")
test_feats.assign(Outcome=y_test_out.values).to_csv(SCRIPT_DIR / "test_components.csv")

# ---------------------------------------------------------------------------
# Level-1: meta-learners on the 3 component probabilities -> Outcome.
# ---------------------------------------------------------------------------
Xm_tr, Xm_te = oof.values, test_feats.values

# (a) Logistic regression  [primary]
logreg = LogisticRegression(max_iter=1000, random_state=RANDOM_STATE)
logreg.fit(Xm_tr, y_train_out.values)
p_lr = logreg.predict_proba(Xm_te)[:, 1]
joblib.dump(logreg, SCRIPT_DIR / "meta_logreg.joblib")

# (b) Noisy-OR analytic baseline (no training)
p_nor = 1.0 - np.prod(1.0 - Xm_te, axis=1)

# (c) Shallow XGBoost meta (reference)
xgb_meta = xgboost.XGBClassifier(
    objective="binary:logistic", random_state=RANDOM_STATE, eval_metric="aucpr",
    max_depth=2, n_estimators=60, learning_rate=0.1,
)
xgb_meta.fit(Xm_tr, y_train_out.values)
p_xgb = xgb_meta.predict_proba(Xm_te)[:, 1]
xgb_meta.save_model(str(SCRIPT_DIR / "meta_xgb.json"))

# Control baseline -- recompute on the SAME test matrix for apples-to-apples.
ctrl = xgboost.XGBClassifier()
ctrl.load_model(str(CONTROL_DIR / "control_xgb_model.json"))
p_ctrl = ctrl.predict_proba(X_test)[:, 1]


def evaluate(name, p):
    yhat = (p >= 0.5).astype(int)
    return {
        "Model": name,
        "AUROC": round(roc_auc_score(y_test_out, p), 4),
        "AUPRC": round(average_precision_score(y_test_out, p), 4),
        "Brier": round(brier_score_loss(y_test_out, p), 4),
        "BalancedAcc": round(balanced_accuracy_score(y_test_out, yhat), 4),
        "F1": round(f1_score(y_test_out, yhat, zero_division=0), 4),
    }


metrics = pd.DataFrame([
    evaluate("Ensemble -- LogReg meta", p_lr),
    evaluate("Ensemble -- Noisy-OR", p_nor),
    evaluate("Ensemble -- XGB meta", p_xgb),
    evaluate("Control (all biomarkers)", p_ctrl),
])
metrics.to_csv(SCRIPT_DIR / "ensemble_metrics.csv", index=False)

# ---------------------------------------------------------------------------
# Report.
# ---------------------------------------------------------------------------
print("\n=== Level-0 head test performance (predicting own component) ===")
for c in COMPONENTS:
    h = head_test_perf[c]
    print(f"  {c}: AUROC {h['AUROC']:.4f}  AUPRC {h['AUPRC']:.4f}  (n_pos_test={h['n_pos_test']})")

print("\nLogReg meta -- component weights (log-odds per unit prob):")
for c, w in zip(COMPONENTS, logreg.coef_[0]):
    print(f"  {c}_pred: {w:+.3f}")
print(f"  intercept: {logreg.intercept_[0]:+.3f}")

print("\n=== Test-set comparison (predicting Outcome) ===")
print(metrics.to_string(index=False))

summary = {
    "components": COMPONENTS,
    "n_folds": N_FOLDS,
    "head_test_perf": head_test_perf,
    "logreg_coef": dict(zip([f"{c}_pred" for c in COMPONENTS], logreg.coef_[0].round(4).tolist())),
    "logreg_intercept": round(float(logreg.intercept_[0]), 4),
    "metrics": metrics.to_dict(orient="records"),
}
(SCRIPT_DIR / "ensemble_summary.json").write_text(json.dumps(summary, indent=2))
print(f"\nSaved heads, meta-models, OOF/test component preds and metrics to:\n  {SCRIPT_DIR}")
